version: "3.3"
services:
  devops:
    image: jppradhan/devops
    ports:
      - "5000:5000"
    depends_on:
      - redis
    deploy:
      replicas: 2
  redis:
    image: redis
    ports:
     - "6379:6379"