version: '3.9'
services:
  devops:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_net
  redis:
    image: redis
    networks:
      - my_net
networks:
  my_net:
    driver: bridge