version: "3.3"
services:
  devops:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - my_net
  redis:
    image: redis
    ports:
     - "6379:6379"
    networks:
      - my_net
networks:
  my_net:
    driver: bridge